config/routes.rb
Rails.application.routes.draw do
  
  resources :shipments

  root 'shipments#new'

  resources :packages, only: [:new, :show, :create, :edit]

end

app/models/package.rb
class Package < ActiveRecord::Base

  attr_accessor :dimension_1, :dimension_2, :dimension_3

end

app/models/shipment.rb
class Shipment < ActiveRecord::Base
  include ActiveMerchant::Shipping

  validates :name, presence: true
  validates :origin_country, presence: true
  validates :origin_city, presence: true
  validates :origin_state, presence: true
  validates :origin_postal_code, presence: true
  validates :country, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :postal_code, presence: true
  validates :length, presence: true
  validates :width, presence: true
  validates :height, presence: true
  validates :weight, presence: true
  

  def origin
    Location.new(country: origin_country, state: origin_state, city: origin_city, postal_code: origin_postal_code)
  end

  def destination
    Location.new(country: country, state: state, city: city, postal_code: postal_code)
  end

  def packages
    package = Package.new(weight, [length, width, height], cylinder: cylinder)
  end

  def get_rates_from_shipper(shipper)
    response = shipper.find_rates(origin, destination, packages)
    response.rates.sort_by(&:price)
  end

  # def ups_rates
  #   ups = UPS.new(login: 'your ups login', password: 'your ups password', key: 'your ups xml key')
  #   get_rates_from_shipper(ups)
  # end

  # def fedex_rates
  #   fedex = FedEx.new(login: ENV['FEDEX_LOGIN'], password: ENV['FEDEX_PASSWORD'], key: ENV['FEDEX_KEY'], account: ENV['FEDEX_ACCOUNT'], :test => true)
  #   get_rates_from_shipper(fedex)
  # end

  def usps_rates
    usps = USPS.new(login: ENV['USPS_ACCOUNT_NUMBER'], password: ENV['USPS_PASSWORD'])
    get_rates_from_shipper(usps)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/create_package_data.rb
module CreatePackageData
  extend ActiveSupport::Concern
	
  def create_dimension_array(dim1, dim2, dim3)
    dimension_array = []
    dimension_array.push(dim1, dim2, dim3)
    return dimension_array.sort!
  end
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController

  include CreatePackageData

  def index
  end

  def show
    @package = Package.find(params[:id])
  end

  def edit
    @package = Package.find(params[:id])
  end  

  def new
    @package = Package.new
  end

  def create
    dim_1 = params[:package][:dimension_1].to_i
    dim_2 = params[:package][:dimension_2].to_i
    dim_3 = params[:package][:dimension_3].to_i

    dimension_array = create_dimension_array(dim_1, dim_2, dim_3)

    height = dimension_array[0]
    width = dimension_array[1]
    length = dimension_array[2]
    
    girth = 2 * (height + width)

    weight = params[:package][:weight]
    zip_origination = params[:package][:zip_origination]
    zip_destination = params[:package][:zip_destination]
    
    @package = Package.new(length: length, 
                            width: width, 
                            height: height, 
                            girth: girth,
                            weight: weight,
                            zip_origination: zip_origination,
                            zip_destination: zip_destination)

    # Save to the database
    if @package.save
      redirect_to @package
    else
      render "new"
    end    
  end


end

app/controllers/shipments_controller.rb
class ShipmentsController < ApplicationController
  def index
    @shipments = Shipment.all
  end

  def show
    @shipment = Shipment.find(params[:id])
  end

  def new
    @shipment = Shipment.new
  end

  def create
    @shipment = Shipment.new(shipment_params)
    if @shipment.save
      redirect_to @shipment, notice: "The shipment has been successfully created.  Below are your shipping options."
    else
      render action: "new"
    end
  end

  def edit
    @shipment = Shipment.find(params[:id])
  end

  def update
    @shipment = Shipment.find(params[:id])
    if @shipment.update_attributes(shipment_params)
      redirect_to @shipment, notice: "The shipment has been successfully updated.  Below are your shipping options."
    else
      render action: "edit"
    end
  end

private

  def shipment_params
    params.require(:shipment).permit(:name, :origin_country, :origin_city, :origin_state, :origin_postal_code, :country, :city, :state, :postal_code, :length, :width, :height, :weight, :cylinder)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/helpers/shipments_helper.rb
module ShipmentsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title
      Frugo
    = stylesheet_link_tag :application, :media => "all"
    = javascript_include_tag :application
    = csrf_meta_tags
  %body
    .frugo-border.frugo-border__north
    .frugo-border.frugo-border__south
    .frugo-border.frugo-border__east
    .frugo-border.frugo-border__west
    .frugo__container
      .frugo__logo
        %h1
          Frugo
      = yield
      .frugo__legal
        %p
          Frugo is an estimated shipping calculator and currently in development.  Use at your own risk. 

app/views/shipments/_form.html.haml
.frugo__new-shipment
  .frugo__instructions
    For length, width, and height, use centimeters.  For weight, use grams.

  - if @shipment.errors.any?
    %ul
      - @shipment.errors.full_messages.each do |message|
        %li
          = message

  = form_for @shipment, :url => {:controller => 'shipments', :action => controller_action} do |f|
    %fieldset.package-form__fieldset
      %legend
        Origin
      .package-form__input
        = f.text_field( :name, :placeholder => "name" ) 
      .package-form__input
        = f.text_field( :origin_country, :placeholder => "origin country" )
      .package-form__input
        = f.text_field( :origin_city, :placeholder => "origin city" )
      .package-form__input
        = f.text_field( :origin_state, :placeholder => "origin state" )
      .package-form__input
        = f.text_field( :origin_postal_code, :placeholder => "origin postal code" )
    %fieldset.package-form__fieldset
      %legend
        Destination 
      .package-form__input
        = f.text_field( :country, :placeholder => "country" )
      .package-form__input
        = f.text_field( :city, :placeholder => "city" )
      .package-form__input
        = f.text_field( :state, :placeholder => "state" )
      .package-form__input
        = f.text_field( :postal_code, :placeholder => "postal code" )
    %fieldset.package-form__fieldset
      %legend
        Package Dimensions
      .package-form__input
        = f.text_field( :length, :placeholder => "length" )
      .package-form__input
        = f.text_field( :width, :placeholder => "width" )
      .package-form__input
        = f.text_field( :height, :placeholder => "height" )
      .package-form__input
        = f.text_field( :weight, :placeholder => "weight" )
      .package-form__input
        = f.label( :cylinder, "cylinder?" )
        = f.check_box :cylinder
    .package-form__input
      = f.submit

app/views/shipments/edit.html.haml
= render :partial => 'form', :locals => { :controller_action => 'update' } 

app/views/shipments/index.html.haml
%h3
  Shipments
  = link_to "New Shipment", new_shipment_path
%table{ :style => " width:100%; text-align:left; " }
  %thead
    %th
      &nbsp;
    %th
      &nbsp;
    %th
      Name
    %th
      Country
    %th
      City
    %th
      State
    %th
      Postal Code
    %th
      Length
    %th
      Width
    %th
      Height
    %th
      Weight
    %th
      Cylinder?
  %tbody
    - @shipments.each do |shipment|
      %tr
        %td
          = link_to "View", shipment
        %td
          = link_to "Edit", edit_shipment_path(shipment)
        %td
          = shipment.name
        %td
          = shipment.country
        %td
          = shipment.city
        %td
          = shipment.state
        %td
          = shipment.postal_code
        %td
          = "#{shipment.length} centimeters"
        %td
          = "#{shipment.width} centimeters"
        %td
          = "#{shipment.height} centimeters"
        %td
          = "#{shipment.weight} grams"
        %td
          = shipment.cylinder ? "Yes" : "No"

app/views/shipments/new.html.haml
- # New Shipment
= render :partial => 'form', :locals => { :controller_action => 'create' }

app/views/shipments/show.html.haml
= link_to("Edit shipment", edit_shipment_path(@shipment))
= link_to("Back to Index", shipments_path)

%h3
  Shipping Information
%table{ :style => "width:100%; text-align:left;" }
  %tr
    %th
      Name
    %th
      Country
    %th
      City
    %th
      State
    %th
      Zip
  %tr
    %td
      = @shipment.name
    %td
      = @shipment.origin_country
    %td
      = @shipment.origin_city
    %td
      = @shipment.origin_state
    %td
      = @shipment.origin_postal_code
  %tr
    %td
      %br
    %td
      = @shipment.country
    %td
      = @shipment.city
    %td
      = @shipment.state
    %td
      = @shipment.postal_code
  %tr
    %th
      Length
    %th
      Width
    %th
      Height
    %th
      Weight
    %th
      Cylinder?
  %tr
    %td
      #{@shipment.length} centimeters
    %td
      #{@shipment.width} centimeters
    %td
      #{@shipment.height} centimeters
    %td
      #{@shipment.weight} grams
    %td
      = @shipment.cylinder ? "Yes" : "No"

%h3
  Shipping Options
%table
  %tr
    %th
      Service Name
    %th
      Price
  / - @shipment.ups_rates.each do |rate|
  /   %tr
  /     %td
  /       = rate.service_name
  /     %td
  /       = number_to_currency(rate.price.to_f / 100)

  / - @shipment.fedex_rates.each do |rate|
  /   %tr
  /     %td
  /       = rate.service_name
  /     %td
  /       = number_to_currency(rate.price.to_f / 100)

  - @shipment.usps_rates.each do |rate|
    %tr
      %td
        = rate.service_name
      %td
        = number_to_currency(rate.price.to_f / 100)